version: '2.2'
services:
  server:
    build:
      context: ../link2-server
      dockerfile: Dockerfile
    init: true
    working_dir: /usr/src/app
    env_file:
      - ./config/common.env
    ports:
      - 3000:3000
    volumes:
      - ../link2-server:/usr/src/app
      - screenshots:/usr/src/app/public/screenshots
      - gem-cache:/gem
    links:
      - screenshot:screenshot
    depends_on:
      - screenshot

  screenshot:
    build:
      context: ../link2-screenshot
      dockerfile: Dockerfile
    init: true
    env_file:
      - ./config/common.env
    ports:
      - 8080:8080
    volumes:
      - screenshots:/usr/src/app/public
      - npm-cache:/usr/src/app/node_modules

  client:
    image: node:8.4.0-alpine
    command: "sh -c 'cd /usr/src/app && yarn && PORT=3001 yarn start'"
    ports:
      - 3001:3001
    volumes:
      - ../link2-client:/usr/src/app
      - npm-cache:/usr/src/app/node_modules

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    command: "bash -c exit 0"
    env_file:
      - ./config/elasticsearch.env
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
volumes:
  esdata:
  npm-cache:
  screenshots:
  gem-cache:
