version: '2.2'
services:
  server:
    build:
      context: ../link2-server
      dockerfile: Dockerfile
    init: true
    working_dir: /usr/src/app
    env_file:
      - ./config/common.env
    ports:
      - 3000:3000
    volumes:
      - ../link2-server:/usr/src/app
    links:
      - screenshot:screenshot
    depends_on:
      - screenshot

  screenshot:
    build:
      context: ../link2-screenshot
      dockerfile: Dockerfile
    init: true
    env_file:
      - ./config/common.env
    ports:
      - 8080:8080
    volumes:
      - ../link2-screenshot/public:/usr/src/app/public
      - npm-cache:/usr/src/app/node_modules

volumes:
  npm-cache:
